apiVersion: batch/v1
kind: Job
metadata:
  name: e2e-tests
spec:
  template:
    spec:
      containers:
      - name: e2e-tests
        image: gcr.io/your-project-id/e2e-tests:latest
        env:
        - name: CONSUMER_SERVICE_URL
          value: "./services/ftgo-consumer-service.yml" 
        - name: RESTAURANT_SERVICE_URL
          value: "./services/ftgo-restaurant-service.yml" 
        - name: ORDER_HISTORY_SERVICE_URL
          value: "/services/ftgo-order-history-service.yml" 
        - name: KITCHEN_SERVICE_URL
          value: "./services/ftgo-kitchen-service.yml"  
        - name: ORDER_SERVICE_URL
          value: "./services/ftgo-order-service.yml" 
        - name: ACCOUNTING_SERVICE_URL
          value: "./services/ftgo-accounting-service.yml"  
        - name: API_GATEWAY_URL
          value: "./services/ftgo-api-gateway.yml"  # Endpoint API Gateway per la comunicazione
      restartPolicy: Never
  backoffLimit: 4
