---
apiVersion: v1
kind: Service
metadata:
  name: ftgo-api-gateway
  labels:
    name: ftgo-api-gateway
    application: ftgo
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    svc: ftgo-api-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftgo-api-gateway
  labels:
    application: ftgo
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        svc: ftgo-api-gateway
        application: ftgo
    spec:
      containers:
      - name: ftgo-api-gateway
        image: us-central1-docker.pkg.dev/ftgo-microservice-project/ftgo-docker-registry/ftgo-api-gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: httpport
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: JAVA_OPTS
          value: -Dsun.net.inetaddr.ttl=30
        - name: ORDER_DESTINATIONS_ORDERSERVICEURL
          value: http://ftgo-order-service:8080
        - name: ORDER_DESTINATIONS_ORDERHISTORYSERVICEURL
          value: http://ftgo-order-history-service:8080
        - name: CONSUMER_DESTINATIONS_CONSUMERSERVICEURL
          value: http://ftgo-consumer-service:8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 20
  selector:
    matchLabels:
      svc: ftgo-api-gateway
      application: ftgo

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ftgo-api-gateway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ftgo-api-gateway
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70