apiVersion: batch/v1
kind: Job
metadata:
  name: ftgo-dynamodb-local-init
spec:
  template:
    spec:
      containers:
      - name: ftgo-dynamodb-local-init
        image: msapatterns/dynamodblocal-init
        env:
        - name: AWS_DYNAMODB_ENDPOINT_URL
          value: http://ftgo-dynamodb-local:8000
        - name: AWS_ACCESS_KEY_ID
          value: FOO_ID
        - name: AWS_SECRET_ACCESS_KEY
          value: FOO_SECRET
      restartPolicy: Never
